version: '3.3'

services:

  otus-nginx:
    image: nginx:1.15
    ports:
      - '6060:80'
    depends_on:
      - otus-php
    networks:
      - shared
    volumes:
      - ./otus/www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  otus-php:
    build: ./otus
    ports:
      - '9001:9001'
    container_name: otus-php
    networks:
      - shared
    volumes:
      - ./otus/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./otus/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./otus/www:/var/www/html
    environment:
          PHP_IDE_CONFIG: "serverName=Docker"


networks:
  shared:
    driver: bridge

volumes:
  redis-data:
